[workspace]
resolver = "2"
members = ["backend", "client", "client_derive", "common"]

[workspace.dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.209", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
